trigger: none
pr: none 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    displayName: terraform validate and init
    jobs:
      -  job: validate
         continueOnError: false
         steps:
         - task: TerraformInstaller@1
           displayName: tfinstall
           inputs:
             terraformVersion: 'latest'
          
 